name: CI workflow

on:
  push:
    branches: main branch
  pull_request:
    branchces: main branch
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
Checkout:
  uses: actions/checkout@v3
Install Dependencies:
  run: python -m pip install --upgrade.pip
  run:pip install -r requirements.txt
